export const ACTIONS_TABLE = 'ActionsTable'
export const NEW_EMAIL_ACTION = 'NewEmailAction'
export const NEW_SMS_ACTION = 'NewSmsAction'
export const NEW_WHATSAPP_ACTION = 'NewWhatsappAction'
export const NEW_FUNNEL_ACTION = 'NewFunnelAction'
