export default {
    isEditing: false,
    funnelId: null,
    description: '',
    isSalesFunnel: true,
    actionTypes: [],
    steps: [],
    active: true,
    showCrudStep: false,
    showCrudAction: false,
    currentStep: 0,
    isEditingStep: false,
    httpErrors: [],
    isLoading: false,
    postbackEventTypes: [],
}
