export const SET_ACTION_ID = 'SET_ACTION_ID'
export const SET_ACTION_TYPE_ID = 'SET_ACTION_TYPE_ID'
export const SET_ACTION_SEQUENCE = 'SET_ACTION_SEQUENCE'
export const SET_ACTION_DESCRIPTION = 'SET_ACTION_DESCRIPTION'
export const ACTION_DATA = 'ACTION_DATA'

export const LOAD_STATE = 'LOAD_STATE'
export const RESET_STATE = 'RESET_STATE'
