export const SET_ID = 'SET_ID'
export const SET_ACTIONS = 'SET_ACTIONS'
export const SET_FUNNEL_STEP_SEQUENCE = 'SET_FUNNEL_STEP_SEQUENCE'
export const SET_ACTION_COMPONENT = 'SET_ACTION_COMPONENT'
export const SET_ACTION_DELETED = 'SET_ACTION_DELETED'
export const SET_POSTBACK_EVENT_TYPE_ID = 'SET_POSTBACK_EVENT_TYPE_ID'

export const ADD_NEW_ACTION = 'ADD_NEW_ACTION'
export const SET_ACTION_EDITING_INDEX = 'SET_ACTION_EDITING_INDEX'
export const UPDATE_ACTION = 'UPDATE_ACTION'
export const DELETE_ACTION = 'DELETE_ACTION'

/* export const UPDATE_ACTION_SEQUENCE = 'UPDATE_ACTION_SEQUENCE' */

export const LOAD_STATE = 'LOAD_STATE'
